global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'node_exporter'
    static_configs:
      - targets: ['node_exporter:9100']

  - job_name: 'ping_exporter'
    static_configs:
      - targets: ['ping_exporter:9427']